[target.aarch64-linux-android]
ar = "/Users/kimi/SDKs/Android/ndk/29.0.13846066/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/kimi/SDKs/Android/ndk/29.0.13846066/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
ar = "/Users/kimi/SDKs/Android/ndk/29.0.13846066/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/kimi/SDKs/Android/ndk/29.0.13846066/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
ar = "/Users/kimi/SDKs/Android/ndk/29.0.13846066/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/kimi/SDKs/Android/ndk/29.0.13846066/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android21-clang"

[target.x86_64-linux-android]
ar = "/Users/kimi/SDKs/Android/ndk/29.0.13846066/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/kimi/SDKs/Android/ndk/29.0.13846066/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-clang"
